### ISSUE TITLE
Question about GT Depth Annotations

### ISSUE THREAD

**Issue by tom-bu** [ruili3/dynamic-multiframe-depth#1]
When you say the "improved ground truth depth," does that correspond to this on the KITTI website "Download annotated depth maps data set (14 GB)"? Does this contain all of the annotations I need to train the model or should I download the other links on the website?

**Comment by ruili3** [comment]
Hi,

Thank you for your interest in our work. We use the same GT depth annotations as in MonoRec. You can get all necessary annotations by downloading the depth map dataset of KITTI (14GB) and processing it using our `preprocess_kitti_transfer_gtdepth_to_odom` script.
