### ISSUE TITLE
is file"data_depth_annotated" wrong in the sequence 03? 

### ISSUE THREAD

**Issue by huangtaokind** [ruili3/dynamic-multiframe-depth#10]
in the "preprocess_kitti_transfer_gtdepth_to_odom.py",
the lib is: `"2011_09_26_drive_0067": "03"`
however when unzipping the data_depth_annotated.zip,
the structure is:
- ...
- 0064_sync
- 0070_sync
- 0084_sync
- ...
whereas the supposed directory"2011_09_26_drive_0067_sync" is missing,
I do not know if this has anything to do with my bug.

**Comment by huangtaokind** [comment]
and on this page,
https://www.cvlibs.net/datasets/kitti/raw_data.php
the 0067 file is also removed

**Comment by ruili3** [comment]
thanks for your interest in the paper.

Did you download the dense depth annotation from the depth estimation page (https://www.cvlibs.net/datasets/kitti/eval_depth.php?benchmark=depth_prediction)? If so, the `preprocess_kitti_transfer_gtdepth_to_odom.py` script should be fine :)

**Comment by chaoying0115** [comment]
我也出现了同样的问题，但发现train_mr_resnet18.json里似乎没有用到03的数据集

**Comment by chaoying0115** [comment]
I also had the same problem, but found that  It seems that the dataset of 03 is not used in train_mr_resnet18.json , so it should not be Impact training

**Comment by ruili3** [comment]
> I also had the same problem, but found that It seems that the dataset of 03 is not used in train_mr_resnet18.json , so it should not be Impact training

thanks for pointing out this!
