### ISSUE TITLE
The problem of calculating dynamic regional indicators

### ISSUE THREAD

**Issue by WangXuCh** [ruili3/dynamic-multiframe-depth#11]
Hello, may I ask how to calculate indicators separately for dynamic areas?Looking forward to your reply!

**Comment by ruili3** [comment]
thanks for your interest

We average depth errors over the intersection of dynamic masks and valid depth masks for dynamic evaluation. You can refer to the [evaluation code](https://github.com/ruili3/dynamic-multiframe-depth/blob/fe59ecbd37c2f108c937baa76121ac3b34802267/evaluater/evaluater.py#L46C13-L46C27) and [metric code](https://github.com/ruili3/dynamic-multiframe-depth/blob/fe59ecbd37c2f108c937baa76121ac3b34802267/model/metric_functions/sparse_metrics.py#L96) for details :)

**Comment by WangXuCh** [comment]
> thanks for your interest
> 
> We average depth errors over the intersection of dynamic masks and valid depth masks for dynamic evaluation. You can refer to the [evaluation code](https://github.com/ruili3/dynamic-multiframe-depth/blob/fe59ecbd37c2f108c937baa76121ac3b34802267/evaluater/evaluater.py#L46C13-L46C27) and [metric code](https://github.com/ruili3/dynamic-multiframe-depth/blob/fe59ecbd37c2f108c937baa76121ac3b34802267/model/metric_functions/sparse_metrics.py#L96) for details :)

Thank you for your reply. How can I train on the Cityscapes dataset?

**Comment by ruili3** [comment]
Just make sure you can get the GT pose for this dataset, and then you can organize the data in a way similar to the KITTI odometry dataset
