### ISSUE TITLE
May I ask how you visualize point clouds and what toolkit are you using?

### ISSUE THREAD

**Issue by WangXuCh** [ruili3/dynamic-multiframe-depth#14]
May I ask how you visualize point clouds and what toolkit you use? Looking forward to your recovery!

**Comment by ruili3** [comment]
We use [create_pointcloud.py](https://github.com/ruili3/dynamic-multiframe-depth/blob/main/create_pointcloud.py) for the point cloud generation. It essentially back projects each image pixel into the 3D space using estimated depth and camera intrinsic. I didn't check `create_pointcloud` before releasing the code so it might raise some issues. Please feel free to report if you find any :)

**Comment by ruili3** [comment]
#16 This is the latest answer for the point cloud generation. Feel free to reopen it.
