### ISSUE TITLE
About the parameter invd_depth_min_max

### ISSUE THREAD

**Issue by WangXuCh** [ruili3/dynamic-multiframe-depth#15]
Excuse me, is your invd_depth_min_max fixed at (0.33, 0.0025) during the experiment? Does it need to be continuously updated through learning like self supervision?

**Comment by ruili3** [comment]
Yes, `invd_depth_min_max ` is fixed during training and inference as we mainly focus on the driving scenarios where the depth range is approximately the same. It's interesting to make `invd_depth_min_max ` a trainable parameter especially when the scene depth range varies for different samples :)

**Comment by WangXuCh** [comment]
> Yes, `invd_depth_min_max ` is fixed during training and inference as we mainly focus on the driving scenarios where the depth range is approximately the same. It's interesting to make `invd_depth_min_max ` a trainable parameter especially when the scene depth range varies for different samples :)

Thank you for your reply! In fact, making invd_depth_min_max a trainable parameter is a common practice in self supervised scenarios.
