### ISSUE TITLE
Depth backbone

### ISSUE THREAD

**Issue by gluefox** [ruili3/dynamic-multiframe-depth#4]
Is it possible to swap the monocular depth estimator to another backbone like Midas?

**Comment by ruili3** [comment]
Hi, we haven't tried Midas. Considering it's trained with scale-invariant loss, you may need to take care of the scale issue when transferring it to our task, which targets producing metric depth.

**Comment by ruili3** [comment]
feel free to reopen if you encountered any issues :)
