### ISSUE TITLE
Question about thresholding photometric error

### ISSUE THREAD

**Issue by myc634** [ruili3/dynamic-multiframe-depth#5]
Great work! Could you give the exact number of the thresholding photometric error and the definition of depth inconsistency?

**Comment by ruili3** [comment]
Thanks for your interest! 
I guess you are referring to the dynamic mask generation for KITTI (which we mentioned in Sec 3.1). You can refer to Sec 3.4 (the last paragraph) of MonoRec paper for details. We use the same mask to evaluate our method on KITTI.

**Comment by myc634** [comment]
ic, thanks for your reply!
