### ISSUE TITLE
Clarification of the results.json metrics

### ISSUE THREAD

**Issue by tom-bu** [ruili3/dynamic-multiframe-depth#6]
I ran the evaluate.py script but I got confused with the different metric variables. Currently, there is metrics, metrics_mv, and metrics_correct. It looks like metrics and metrics_correct are the same and metrics_mv is the dynamic objects metric. Are there any more details for metrics and metrics_correct?

Thanks

**Comment by ruili3** [comment]
Hi,

The `metrics_correct` may be initially designed to monitor the model behaviors during the training phase. It weighs the metrics of the current batch and the metric of previous batches separately, then combines them together, which is suitable for online monitoring. The implementation here is consistent with MonoRec. The `metrics` and `metrics_mv` are used for evaluation purposes, where all metrics are first cumulated and then averaged over all batches. In terms of evaluation, the results of `metrics_correct` and `metrics` are consistent, so you can directly refer to the scores of `metrics` and `metrics_mv`.
